In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# Python program to demonstarte
# basic array characteristics

In [13]:
import numpy as np

In [ ]:
# Creating array object
arr = np.array([[1,2,3],
                 [4,2,5]])

In [15]:
# Printing shape of array
print ("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [19]:
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

Size of array:  6


In [21]:
#Printing type of elements in array
print("Array stores elements of type:", arr.dtype)

Array stores elements of type: int32


In [23]:
#printing type of arr object
print("Array is of type:", type(arr))

Array is of type: <class 'numpy.ndarray'>


In [25]:
#printing array dimensions(axes)
print ("No. of dimensions:", arr.ndim)

No. of dimensions: 2


In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print(my_list)

In [305]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [307]:
'''Now let's multiply each sequence by 2:'''
%time for _ in range(10): my_arr2=my_arr * 2
%time for _ in range(10): my_list2=[x*2 for x in my_list]
display(my_arr2)
display(my_list2)

CPU times: total: 15.6 ms
Wall time: 18.9 ms
CPU times: total: 609 ms
Wall time: 631 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [ ]:
In [12]: import numpy as np
#Generate some random data
In [13]: data=np.random.random(2, 3)
In [14]: print(data)
# I then write mathematical operations with data:
In [15]: print(data * 10)
In [16]: print(data + data)

In [43]:
a = np.array([1,2,3])

In [47]:
a

array([1, 2, 3])

In [49]:
a.dtype

dtype('int32')

In [51]:
b = np.array(["a", "b", "c"])

In [53]:
b

array(['a', 'b', 'c'], dtype='<U1')

In [55]:
a

array([1, 2, 3])

In [59]:
a[2] = 99

In [61]:
a

array([ 1,  2, 99])

In [65]:
aL = [1,2,3]

In [67]:
aL.append(33)

In [69]:
aL

[1, 2, 3, 33]

In [79]:
a

array([ 1,  2, 99])

In [81]:
a[:2]

array([1, 2])

In [83]:
aL

[1, 2, 3, 33]

In [85]:
aL*2

[1, 2, 3, 33, 1, 2, 3, 33]

In [87]:
a

array([ 1,  2, 99])

In [89]:
a* 2

array([  2,   4, 198])

In [91]:
import sys

In [93]:
#declaring a list of 1000 elements
S = range(1000)

#printing size of each element of the list
print("Size of each element of list in bytes:", sys.getsizeof(S))

#printing size of the whole list
print ("Size of the whole list in bytes:", sys.getsizeof(S)*len(S))

#declaring a Numpy array of 1000 elements
D = np.arange(1000)

#printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes:", D.itemsize)

#printing size of the whole Numpy array
print ("Size of the whole Numpy array in bytes:", D.size*D.itemsize)

Size of each element of list in bytes: 48
Size of the whole list in bytes: 48000
Size of each element of the Numpy array in bytes: 4
Size of the whole Numpy array in bytes: 4000


In [95]:
import numpy as np

In [99]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [101]:
display(type(arr1))

numpy.ndarray

In [103]:
print (arr1.shape)

(5,)


In [ ]:
In [13]: data=np.random.random(1, 3)
In [14]: print(data)
data.shape

In [123]:
In [13]: data=np.array([1,2,3,4,5])
In [14]: print(data)
data.shape

[1 2 3 4 5]


(5,)

In [125]:
In [13]: data=np.array([[1,2,3,4,5]])
In [14]: print(data)
data.shape

[[1 2 3 4 5]]


(1, 5)

In [129]:
In [13]: data=np.array([[1,2,3,4,5], [33,44,55,66,77]])
In [14]: print(data)
data.shape

[[ 1  2  3  4  5]
 [33 44 55 66 77]]


(2, 5)

In [131]:
In [13]: data=np.array([[[1,2,3,4,5], [33,44,55,66,77]], [[1,2,3,4,5], [33,44,55,66,77]]])
In [14]: print(data)
data.shape

[[[ 1  2  3  4  5]
  [33 44 55 66 77]]

 [[ 1  2  3  4  5]
  [33 44 55 66 77]]]


(2, 2, 5)

In [133]:
In [13]: data=np.array([[[1,2,3,4,5], [33,44,55,66,77]]])
In [14]: print(data)
data.shape

[[[ 1  2  3  4  5]
  [33 44 55 66 77]]]


(1, 2, 5)

In [151]:
data.ndim

2

In [159]:
In [13]: data=np.array([[1,2,3,4,5], [33,44,55,66,77]])
In [14]: print(data)
data.shape

[[ 1  2  3  4  5]
 [33 44 55 66 77]]


(2, 5)

In [149]:
data.dtype

dtype('int32')

In [155]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [161]:
np.zeros((2,3,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [163]:
np.zeros((7,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [169]:
np.empty((7,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [171]:
np.empty((10,4,6))

array([[[ 2.72882326e+079,  2.37711102e-259,  2.64686750e+180,
          5.30200563e+005,  3.02876088e-152,  1.94901496e+227],
        [ 2.17768373e+243,  5.57844892e+228,  2.32207754e-152,
          5.98189647e-154,  2.44045298e-152,  3.99279672e+252],
        [ 4.26209413e+180,  2.31881454e-152,  1.96086582e+243,
          3.84568576e-086,  2.19340302e-152,  6.53442689e-095],
        [ 1.14219901e+243,  4.25481362e+228,  5.00881312e+223,
          1.35710728e+166,  1.14323016e+243,  1.10765090e+039]],

       [[ 1.47716199e+248,  3.81431017e+228,  3.99909290e+252,
          4.47593784e-091,  4.47593816e-091,  4.47593816e-091],
        [ 4.47593816e-091,  6.19640460e+223,  2.45652619e+198,
          1.99721148e+161,  2.35287091e+251,  1.02945576e+248],
        [ 2.18185285e+243,  6.98860378e+228,  1.10227718e+200,
          3.09391800e+169,  6.01099880e+175,  5.04044092e+180],
        [ 7.34292335e+223,  4.77092982e+180,  5.03734956e+175,
          1.70887677e+214,  6.97379750e+228,  

In [173]:
np.zeros((10,4,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],


In [179]:
data2 = [1,2,3,4,5,6]
a = np.array(data2)
a

array([1, 2, 3, 4, 5, 6])

In [181]:
a[3]

4

In [183]:
a[-3]

4

In [185]:
a[2:3]

array([3])

In [191]:
a.shape

(6,)

In [203]:
data2D = ([[1,2,3,4],[5,6,7,8]])
b = np.array(data2D)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [205]:
b.shape

(2, 4)

In [217]:
#how to get 6 out

In [219]:
b[1:1]

array([], shape=(0, 4), dtype=int32)

In [221]:
b[1,1:2]

array([6])

In [225]:
data3D = ([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
c = np.array(data3D)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [235]:
#how to get 19
c[2,0,2]

19

In [237]:
c[2,0,2:3]

array([19])

In [247]:
c[2:3,0,2]

array([19])

In [263]:
a=[1,2]
print(np.asarray(a))
print("/n")

import numpy as np
x = np.arange(6)
x = x.reshape((2,3))
print(x)
print(np.ones_like(x))
print("/n")
print(np.zeros_like(x))
print("/n")
print(np.empty_like(x))

[1 2]
/n
[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]
/n
[[0 0 0]
 [0 0 0]]
/n
[[0 0 0]
 [0 0 0]]


In [265]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr= arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [267]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [269]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype =np.string_ )
numeric_strings.astype(float)
                         

array([ 1.25, -9.6 , 42.  ])

In [275]:
numeric_strings = np.array(['1', '-9', '42'], dtype =np.string_ )
numeric_strings.astype(np.int32)
                         

array([ 1, -9, 42])

In [309]:
import os, sys
os.path.dirname(sys.executable)

'C:\\Users\\USER\\anaconda3'

In [2]:
import numpy as np

In [8]:
try:
    numeric_strings= np.array(['1.25', '-9.6', '42'], dtype=np.string_)
    numeric_strings.astype(float)
    print("It all worked")
except Exception as e:
    # Handle any other exceptions that are not specifically caught
    print(f"An unexpected error occurred: {e}")

It all worked


In [14]:
try:
    numeric_strings= np.array(['1.25E', '-9.6', '42'], dtype=np.string_)
    numeric_strings.astype(float)
    print("It all worked")
except Exception as e:
    # Handle any other exceptions that are not specifically caught
    print(f"An unexpected error occurred: {e}")
print("Way to go, exceptions are the best")

An unexpected error occurred: could not convert string to float: b'1.25E'
Way to go, exceptions are the best


In [16]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
display(arr*arr)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [22]:
display(arr - arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
arr2 = np.array([[0.,4.,1.], [7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [30]:
display(arr2 > arr)

array([[False,  True, False],
       [ True, False,  True]])

In [52]:
#import all the necessary libraries
import numpy as np

In [259]:
import matplotlib.pyplot as plt

In [257]:
#defining a user-defined function to plot the three-dimensional scatter plot
def three_dimensional_scatter(x1,y1,z1,x2,y2,z2):
    #creating figure object in the plot
    fig = plt.figure(figsize = (9,))
    #created three-dimensional workspace
    ax = fig.add_subplot(111, projection="3d")
    #plotting the first three-dimensional scatter plot using the parameters
    ax.scatter3D(x1,y1,z1,color = "green")
    #plotting the second three-dimensional scatter plot using the parameters
    ax.scatter3D(x2,y2,z2,color = "red")
    #defining title to the plot
    plt.title("Creating three-dimensional scatter plot using matplotlib and numpy")
    #defining legends to the plot
    plt.legend(["first", "second"])
    #displaying the three-dimensional scatter plot
    ptl.show()

<module 'matplotlib.pyplot' from 'C:\\Users\\USER\\anaconda3\\Lib\\site-packages\\matplotlib\\pyplot.py'>


In [56]:
#Creating the main() function
def main():
    #creating data points for the z-axis
    z1 = np.arange(0,150,1)
    #creating data points for the x-axis
    x1 = np.random.randint(8000,size = (150))
    #creating data points for the y-axis
    y1 = np.random.randint(800,size =(150))
    z2 = np.arange(0,150,1)
    #creating data points for the x-axis
    x2 = np.random.randint(8000,size = (150))
    #creating data points for the y-axis
    y2 = np.random.randint(800,size =(150))
    #calling the main() function
    three_dimensional_scatter(x1,y1,z1,x2,y2,z2)

#declaring the main() function as the driving code of the program.
if __name__ == "_main_":
    main()

In [66]:
#how to get 4,5,6,
L1 = [1,2,3,4,5,6,7,8,9]
sL1= L1[3:6]
print(L1)
print(sL1)
sL1[1] =99
print(sL1)
print(L1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6]
[4, 99, 6]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [68]:
L1 = np.array([1,2,3,4,5,6,7,8,9])
sL1= L1[3:6]
print(L1)
print(sL1)
sL1[1] =99
print(sL1)
print(L1)

[1 2 3 4 5 6 7 8 9]
[4 5 6]
[ 4 99  6]
[ 1  2  3  4 99  6  7  8  9]


In [78]:
arr = np.arange(10)
print("Print the original array")
print(arr)
arr[5]
print(arr[5:8])
arr[5:8] =12
print("Print the original array after changing")
print(arr)
arr_slice= arr[5:8]
print("Print the slice of the original array")
print(arr_slice)
print("Print the original array again")
print(arr)


Print the original array
[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
Print the original array after changing
[ 0  1  2  3  4 12 12 12  8  9]
Print the slice of the original array
[12 12 12]
Print the original array again
[ 0  1  2  3  4 12 12 12  8  9]


In [88]:
arr2d = np.array([[1,2,3,], [4,5,6], [7,8,9]])
print(arr2d)
print("Dim:" + str(arr2d.ndim))
print("shape:" + str(arr2d.shape))
display("arr2d[2] will show higher dimension")
arr2d[2]
display("arr2d[0][2] will show either sclar or 1D objects")
arr2d[0][2]
display("arr2d[0,2] will show either sclar or 1D objects")
arr2d[0,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dim:2
shape:(3, 3)


'arr2d[2] will show higher dimension'

'arr2d[0][2] will show either sclar or 1D objects'

'arr2d[0,2] will show either sclar or 1D objects'

3

In [106]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3d.ndim)
print(arr3d.shape)
arr3d
arr3d[0]

3
(2, 2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr3d[0,0]

1

In [116]:
arr3d[0,0,0]
arr3d[0,0,0:1]

array([1])

In [120]:
#how to get 1and 3, 7 and 9
arr2d= np.array([[1,2,3],[4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
arr2d[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [126]:
arr2d[::2,::2]

array([[1, 3],
       [7, 9]])

In [128]:
arr2d[1,0:2]

array([4, 5])

In [132]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
arr2d[2, ::]

array([7, 8, 9])

In [136]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [138]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [160]:
arr2d[:, 0:1]

array([[1],
       [4],
       [7]])

In [142]:
names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Joe' 'Joe']
[[ 0.04618038  0.32717429  0.0277848  -1.12576777]
 [-1.17633253  1.33631723 -0.37198496  0.70289029]
 [ 1.93602083 -0.11836958 -0.09413729 -0.73520442]
 [-0.49729873 -1.26132627  0.82137709  0.04619628]
 [-0.01678345 -1.09071079 -0.8081249   0.90066317]
 [-0.28684881 -1.21693115 -0.2506713   0.28907284]
 [ 0.87336848 -0.13633383 -1.04466753  0.92165577]]


In [158]:
selection = names == 'Joe'
print(selection)

[False  True False  True  True]


In [162]:
names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
print(data)
print(data < 0)
print(data)

[[-0.80846999  1.23937959 -0.06207279 -0.05694836]
 [-1.1743225   2.09993864 -0.22082644 -0.96021365]
 [-1.02993384  0.69114609 -0.98277652  0.08443745]
 [-0.52843818  0.95537997  0.27724853  0.94617666]
 [ 0.46943196 -0.26140614  0.51617809 -2.39252997]
 [ 0.93875612  0.64407655 -0.03874314  1.47333793]
 [-0.33997703 -0.3500785  -0.43508238 -0.0920552 ]]
[[ True False  True  True]
 [ True False  True  True]
 [ True False  True False]
 [ True False False False]
 [False  True False  True]
 [False False  True False]
 [ True  True  True  True]]
[[-0.80846999  1.23937959 -0.06207279 -0.05694836]
 [-1.1743225   2.09993864 -0.22082644 -0.96021365]
 [-1.02993384  0.69114609 -0.98277652  0.08443745]
 [-0.52843818  0.95537997  0.27724853  0.94617666]
 [ 0.46943196 -0.26140614  0.51617809 -2.39252997]
 [ 0.93875612  0.64407655 -0.03874314  1.47333793]
 [-0.33997703 -0.3500785  -0.43508238 -0.0920552 ]]


In [170]:
data[data < 0] =0
print(data)

[[0.         1.23937959 0.         0.        ]
 [0.         2.09993864 0.         0.        ]
 [0.         0.69114609 0.         0.08443745]
 [0.         0.95537997 0.27724853 0.94617666]
 [0.46943196 0.         0.51617809 0.        ]
 [0.93875612 0.64407655 0.         1.47333793]
 [0.         0.         0.         0.        ]]


In [186]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [188]:
arr[[2,5,0]]

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.]])

In [190]:
arr = np.arange(32)
print(arr)
arr2 = arr.reshape(8,4)
print(arr2)

arr =np.arange(32).reshape(8,4)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [192]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [214]:
arr[[1,5,7,2],[2,0,1,0]]

array([ 6, 20, 29,  8])

In [200]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [204]:
arr[[1,5,7,2]][:0, [0,3,1,2]]

array([], shape=(0, 4), dtype=int32)

In [212]:
np_array_1s = np.array([[1,1,1],[1,1,1]])
np_array_9s = np.array([[9,9,9],[9,9,9]])
display(np.concatenate([np_array_1s, np_array_9s], axis = 0))
display(np.concatenate([np_array_1s, np_array_9s], axis = 1))                       

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [216]:
arr=np.random.randn(4,4)
arr

array([[ 0.5503429 , -0.4655375 ,  0.064885  , -1.2543965 ],
       [-0.74682949,  0.36431049,  0.03370836, -1.02942075],
       [ 0.36630497, -0.09182971, -1.75366936, -0.27647259],
       [ 0.49351146, -1.05928394, -0.64772995, -0.35989606]])

In [220]:
np.where(arr > 0,2,-2)

array([[ 2, -2,  2, -2],
       [-2,  2,  2, -2],
       [ 2, -2, -2, -2],
       [ 2, -2, -2, -2]])

In [222]:
arr > 0

array([[ True, False,  True, False],
       [False,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [224]:
np.where(arr > 0, 2,arr) #set only positive values to 2

array([[ 2.        , -0.4655375 ,  2.        , -1.2543965 ],
       [-0.74682949,  2.        ,  2.        , -1.02942075],
       [ 2.        , -0.09182971, -1.75366936, -0.27647259],
       [ 2.        , -1.05928394, -0.64772995, -0.35989606]])

In [226]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.where(arr2d < 5,1,np.where(arr2d >=7,0,2))# if arr is <5 put 1,else if >=7 then put 0 else put 2

array([[1, 1, 1],
       [1, 2, 2],
       [0, 0, 0]])

In [235]:
arr=np.random.randn(100)
(arr>0).sum()

53

In [237]:
arr=np.random.randn(6)
arr

array([ 1.13973247, -0.33563036, -2.27602294,  0.49905809, -0.30567261,
       -0.22697954])

In [241]:
arr.sort()
arr

array([-2.27602294, -0.33563036, -0.30567261, -0.22697954,  0.49905809,
        1.13973247])

In [243]:
names= np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [245]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [247]:
sorted(set(names))

['Bob', 'Joe', 'Will']